### ISSUE TITLE
Mac Javascript error on every song change and no notifications

### ISSUE THREAD

**Issue by joshnat** [adlerluiz/ytmdesktop#10]
On every song change.  OSX 10.13.6

**A JavaScript error occurred in the main process**
```Uncaught Exception:
TypeError: Cannot read property 'on' of undefined
    at new Notification (/Applications/YouTube Music Desktop App.app/Contents/Resources/app.asar/node_modules/electron-native-notification/index.js:55:14)
    at Object.exports.balloon (/Applications/YouTube Music Desktop App.app/Contents/Resources/app.asar/tray.js:103:13)
    at updateActivity (/Applications/YouTube Music Desktop App.app/Contents/Resources/app.asar/main.js:198:14)
    at /Applications/YouTube Music Desktop App.app/Contents/Resources/app.asar/main.js:179:29
    at EventEmitter.<anonymous> (/Applications/YouTube Music Desktop App.app/Contents/Resources/electron.asar/browser/api/web-contents.js:157:45)
    at Object.onceWrapper (events.js:273:13)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/YouTube Music Desktop App.app/Contents/Resources/electron.asar/browser/api/web-contents.js:347:21)
    at WebContents.emit (events.js:182:13)

**Comment by rickinbsb** [comment]
@joshnat what ytmdesktop version are you on?

**Comment by joshnat** [comment]
I'm on 1.2.3.  If there's a newer version I'm not sure where to find it.  I downloaded from https://ytmdesktop.app/.

**Comment by adlerluiz** [comment]
@joshnat Did you just install and start the first time, and did this error occur?

**Comment by joshnat** [comment]
@adlerluiz that's correct.  I'm now running for several minutes without problems.

**Comment by adlerluiz** [comment]
Great, it's working, but i'll investigate this case, if it happens again, please do not forget to warn again, thank you

**Comment by gcsomesz** [comment]
> Great, it's working, but i'll investigate this case, if it happens again, please do not forget to warn again, thank you

Same here:

A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'on' of undefined
    at new Notification (/Applications/YouTube Music Desktop App.app/Contents/Resources/app.asar/node_modules/electron-native-notification/index.js:55:14)
    at Object.exports.balloon (/Applications/YouTube Music Desktop App.app/Contents/Resources/app.asar/tray.js:103:13)
    at updateActivity (/Applications/YouTube Music Desktop App.app/Contents/Resources/app.asar/main.js:198:14)
    at /Applications/YouTube Music Desktop App.app/Contents/Resources/app.asar/main.js:179:29
    at EventEmitter.<anonymous> (/Applications/YouTube Music Desktop App.app/Contents/Resources/electron.asar/browser/api/web-contents.js:157:45)
    at Object.onceWrapper (events.js:273:13)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/YouTube Music Desktop App.app/Contents/Resources/electron.asar/browser/api/web-contents.js:347:21)
    at WebContents.emit (events.js:182:13)
