### ISSUE TITLE
safeStorage secrets are broken on Linux using xdg-desktop-portal

### ISSUE THREAD

**Issue by ProjectSynchro** [adlerluiz/ytmdesktop#1428]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

When using the "`gnome-libsecret`" safeStorage backend, a secret is created. After logging into Google and closing the application, it forgets your login credentials.

Using the "`basic`" safeStorage backend allows you to login to Google and the secret is saved, however you then cannot log in to last.fm.

### Expected Behavior

Using the "`gnome-libsecret" backend should allow the same google login credentials to be used.

Using the "`basic`" backend should allow you to save your lastfm credentials.

### Steps To Reproduce

Clone the my Git fork here:
https://github.com/ProjectSynchro/app.ytmdesktop.ytmdesktop

Checkout the safestorage-fix branch

Build the flatpak with `flatpak-builder --install build-dir ./app.ytmdesktop.ytmdesktop.yml  --force-clean --user`
(This builds and installs the flatpak locally for use)

Run the Flatpak with: `flatpak run app.ytmdesktop.ytmdesktop//master`
(This runs the locally built flatpak)

To reproduce the issue seen with "`gnome-libsecret`" backend

Launch the Linux Binary with `--password-store="gnome_libsecret"`
(Set the line in [app.ytmdesktop.ytmdesktop.yml](https://github.com/ProjectSynchro/app.ytmdesktop.ytmdesktop/blob/48011a52197d0477c47fc16d7d7b70e3ffd15a84/app.ytmdesktop.ytmdesktop.yml#L81) and rebuild)

This is present intermittently in non-sandboxed Linux. (using this backend in a KDE desktop environment.

1. Login to Google
2. Relaunch Application 

To reproduce the issue seen with "basic" backend not working with lastfm integration:
(Set the line in [app.ytmdesktop.ytmdesktop.yml](https://github.com/ProjectSynchro/app.ytmdesktop.ytmdesktop/blob/48011a52197d0477c47fc16d7d7b70e3ffd15a84/app.ytmdesktop.ytmdesktop.yml#L81) and rebuild)

This is also present in non-sandboxed Linux.

1. Launch the Linux Binary with the `--password-store="basic"` flag.
2. Try and log in to last.fm (Observe issue seen in #1427) 

### YTMDesktop

v2.0.5

### OS

Linux

### OS Version

Fedora Rawhide

### Arch

x64

### Installation way

Flatpak (Derived from Debian package)

**Comment by NovusTheory** [comment]
By not allowing you to login to last.fm is this the application showing that safeStorage isn't available? We use Electron's [safeStorage.isEncryptionAvailable()](https://www.electronjs.org/docs/latest/api/safe-storage#safestorageisencryptionavailable) API for this. I don't think we explicitly forbid certain backends so I'm not sure why Electron would be saying it's not available if it is.

As for the Google login issue though that is a very odd issue since that is entirely controlled by Chromium. [We explicitly set the EnableCookieEncryption fuse](https://github.com/ytmdesktop/ytmdesktop/blob/development/forge.config.ts#L125) which tells Chromium to encrypt the cookies on disk and using one backend versus the other shouldn't make a difference with the cookies being "forgotten" (wiped because it can't decrypt?).

**Comment by ProjectSynchro** [comment]
~~I think I have found the core issue at fault: https://github.com/electron/electron/issues/39789~~ Nope

It seems like the backend safeStorage selects falls over when the value of `XDG_CURRENT_DESKTOP` is outside of predefined desktop environments (or empty!).

I think the only way to get around this in a sandbox is to select an environment variable on their supported list, I'll try that shortly and post my results here.

According to a nixOS packager this bug is fixed in Electron 30  (or at least doesn't appear), but I don't see any official verification of that, so I'm not sure if it is or not. 

This may also solve the issue of lastfm not working with the basic backend selected.

It may be worth keeping this issue open here to keep track of that bug, I suspect it will affect users that don't use standard desktop environments (or ones that don't set `XDG_CURRENT_DESKTOP`.

**Comment by ProjectSynchro** [comment]
No dice when setting `XDG_CURRENT_DESKTOP` to "unity".

I was able to get into the lastfm integration settings. After connecting ytmdesktop to lastfm however the integration doesn't seem to work.

Relevant log lines:
```
[main][info] Starting enabled integrations
[main][error] Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at t.default.getSettings (/app/lib/youtube-music-desktop-app/resources/app.asar/.webpack/main/index.js:8:455510)
    at t.default.enable (/app/lib/youtube-music-desktop-app/resources/app.asar/.webpack/main/index.js:8:454343)
    at App.<anonymous> (/app/lib/youtube-music-desktop-app/resources/app.asar/.webpack/main/index.js:8:422141)

```

EDIT: https://github.com/electron/electron/issues/32598
https://github.com/flathub/com.vscodium.codium/issues/239
These issues may help.

The secret does indeed exist, so there's some other issue going on here.

> By not allowing you to login to last.fm is this the application showing that safeStorage isn't available? We use Electron's [safeStorage.isEncryptionAvailable()](https://www.electronjs.org/docs/latest/api/safe-storage#safestorageisencryptionavailable) API for this. I don't think we explicitly forbid certain backends so I'm not sure why Electron would be saying it's not available if it is.

Sorry, forgot to reply to this point. Yes the application is showing that safeStorage isn't available, even with the "basic" backend manually selected. This is reproducable with the standard linux packages as well (outside of a sandbox).

**Comment by ProjectSynchro** [comment]
I was poking around here: https://github.com/ytmdesktop/ytmdesktop/blob/ead0bbd58d52fa7e3f4cf060fc7aacedccb94459/src/main/index.ts#L1438-L1442

Looking at this section in the electron docs:
> Note that not all Linux setups have an available secret store. If no secret store is available, items stored in using the safeStorage API will be unprotected as they are encrypted via hardcoded plaintext password. You can detect when this happens when safeStorage.getSelectedStorageBackend() returns basic_text.

It could be that in this "unprotected" state, `isEncryptionAvailable` returns false as the secret isn't properly "encrypted".

**Comment by ProjectSynchro** [comment]
I think the best way forward would be to get the "basic" backend working, as if the "basic" backend is configured, cookie encryption works as well. See: https://www.electronjs.org/docs/latest/tutorial/fuses#cookieencryption

> The cookieEncryption fuse toggles whether the cookie store on disk is encrypted using OS level cryptography keys.

My guess is the "OS level cryptography keys" are also influenced by the `--password-store` flag in some way, as the behaviour changes when the backend is changed.

My guess is there's a bug somewhere in electron that is rearing it's head. I am unfortunately out of my depth as I normally don't go into Electron-land.

**Comment by NovusTheory** [comment]
Thanks for all this information. I personally have used an install of EndeavourOS with KDE Plasma and didn't experience issues with safeStorage nor the google login. I wonder if all kwallet stores work and the only one acting up is gnome_libsecret and that could likely be an upstream problem in all cases.

Something to test might be to upgrade Electron for the app to the latest, even the latest alphas/betas/nightlies of Electron, and see if it still applies as well.

In any case I would *prefer* to avoid supporting basic if a fix can be obtained without it since that defeats the purpose of using safeStorage but I am open to allowing it as it's the users choice and can possibly present a warning in the app the first time it's detected.

**Comment by stimut** [comment]
FYI I discovered that this issue is specific to the flatpak install. It's because flatpak blocks communication on d-bus, which is what Electron uses to determine if a password storage service (and so `safeStorage`) is available.

I have submitted a PR to have the flatpak manifest for the app fixed: https://github.com/flathub/app.ytmdesktop.ytmdesktop/pull/38
