### ISSUE TITLE
App crash on windows startup from updateFromStore function

### ISSUE THREAD

**Issue by mdechdee** [adlerluiz/ytmdesktop#1446]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

App crash on windows startup probably related to updateFromStore function

### Expected Behavior

App should not crash on startup

### Steps To Reproduce

1. Enable auto startup
2. Turn on your machine
3. Boom! scary crash appeared!

It's only happened once though, when i restarted the app, the problem is gone.
Probably low priority ¯\\_(ツ)_/¯

### YTMDesktop

v2.0.5

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

### Anything else?

YouTube Music Desktop App Crashed

Environment Details:
    YouTube Music Desktop App 2.0.5
    Electron 29.0.1
    Windows NT 10.0.22631

Name: TypeError
Message: Cannot read properties of undefined (reading 'map')
Cause: Unknown

TypeError: Cannot read properties of undefined (reading 'map')
    at p (C:\Users\gozzz\AppData\Local\youtube_music_desktop_app\app-2.0.5\resources\app.asar\.webpack\main\index.js:8:460522)
    at d (C:\Users\gozzz\AppData\Local\youtube_music_desktop_app\app-2.0.5\resources\app.asar\.webpack\main\index.js:8:460985)
    at Array.map (<anonymous>)
    at Object.updateFromStore (C:\Users\gozzz\AppData\Local\youtube_music_desktop_app\app-2.0.5\resources\app.asar\.webpack\main\index.js:8:462970)
    at IpcMainImpl.<anonymous> (C:\Users\gozzz\AppData\Local\youtube_music_desktop_app\app-2.0.5\resources\app.asar\.webpack\main\index.js:8:416054)
    at IpcMainImpl.emit (node:events:514:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:77786)
    at WebContents.emit (node:events:514:28)

**Comment by Alipoodle** [comment]
Appears that we only check if there is a Queue but not check if the queue has any items inside of it in that statement 🤔

I suspect it would likely be a 1 time crash as we play a bit of a Mouse catching game to know when YTM's Player details load and our internal stuff load.

There's a few areas like this we need to do better checks to prevent it crashing in random cases of YTM not providing everything or half the data.
