### ISSUE TITLE
Playlist crash alert

### ISSUE THREAD

**Issue by PenguinzTech** [adlerluiz/ytmdesktop#1476]
### Consent

- [x] I verified that there is no open/closed issue for the same subject.
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Crashing when I click on any playlist

### Expected Behavior

We be jammin' with music from this great idea!

### Steps To Reproduce

1. OPen YT Music on Win10
2. click on any playlist 
3. crash time with the error:

```
YouTube Music Desktop App Crashed

Environment Details:
    YouTube Music Desktop App 2.0.6
    Electron 33.0.2
    Windows NT 10.0.19045

Name: TypeError
Message: Cannot read properties of undefined (reading 'map')
Cause: Unknown

TypeError: Cannot read properties of undefined (reading 'map')
    at d (C:\Users\Penguinz\AppData\Local\youtube_music_desktop_app\app-2.0.6\resources\app.asar\.webpack\main\index.js:8:461705)
    at f (C:\Users\Penguinz\AppData\Local\youtube_music_desktop_app\app-2.0.6\resources\app.asar\.webpack\main\index.js:8:462168)
    at Array.map (<anonymous>)
    at Object.updateFromStore (C:\Users\Penguinz\AppData\Local\youtube_music_desktop_app\app-2.0.6\resources\app.asar\.webpack\main\index.js:8:464926)
    at IpcMainImpl.<anonymous> (C:\Users\Penguinz\AppData\Local\youtube_music_desktop_app\app-2.0.6\resources\app.asar\.webpack\main\index.js:8:416925)
    at IpcMainImpl.emit (node:events:519:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:86280)
    at WebContents.emit (node:events:519:28)
```

### YTMDesktop

2.0.6

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

### Anything else?

Hoping can fix as I love the app!

**Comment by PenguinzTech** [comment]
For follow up - I tried re-installing to see if that would solve the issue. it does not.
Interesting though, even when the message pops up, the music keeps playing.. but cannot  do anything with the app due to the popup

**Comment by Alipoodle** [comment]
I can sadly tell you that "Clicking a playlist and crashing" is not a issue which is consistent.
We have trace log so we can compare it to a build of the app and see which are is failing though.
